version: '3.7'

networks:
  default: 
    name: exbuilder_deployer
    
services:
    postgres:
      image: postgres:10
      command: ["postgres", "-c", "log_statement=all"]
      container_name: postgres
      restart: unless-stopped
      tty: true
      ports: 
        - "${DB_PORT}:${DB_PORT}"
      volumes:
        - ./exbuilder_db/data:/var/lib/postgresql/data
        - ./exbuilder_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment: 
        POSTGRES_DATABASE: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
        SERVICE_TAGS: dev
        SERVICE_NAME: postgres
    
  app:
    image: 'jc21/nginx-proxy-manager:2.8.0'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    container_name: nginxproxymanager
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "${DB_PASSWORD}"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
  db:
    image: 'jc21/mariadb-aria:10.4.15'
    container_name: nginxproxymanager_db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./data/mysql:/var/lib/mysql
